import {
  mkdir,
  access,
  readdir,
  readFile,
  rm,
  rmdir,
  writeFile,
} from "node:fs/promises";
import { createHash } from "node:crypto";
import path from "node:path";

/**
 * CRLF and lone CR -> LF, at the byte level (no decoding, so any content is
 * handled exactly). Arcane's managed files are text, and git rewrites their
 * line endings on checkout (`text=auto eol=lf`, `core.autocrlf`); a hash that
 * saw those bytes read a file nobody had edited as an operator edit -- found
 * live in the CS-03 migration fixture (TODO.md, "a recorded file hash is
 * byte-exact").
 */
function normalizeLineEndings(content: Buffer): Buffer {
  if (!content.includes(0x0d)) return content;
  const out = Buffer.allocUnsafe(content.length);
  let o = 0;
  for (let i = 0; i < content.length; i++) {
    const byte = content[i]!;
    if (byte === 0x0d) {
      out[o++] = 0x0a;
      if (content[i + 1] === 0x0a) i++;
      continue;
    }
    out[o++] = byte;
  }
  return out.subarray(0, o);
}

/**
 * SHA-256 hex digest of content with line endings normalized to LF -- the
 * hash `fileHashes` and the user tier's `fanout` record carry (ARC-038
 * decision 1). Two files that differ only in CRLF/LF hash the same.
 */
export function hashContent(content: Buffer | string): string {
  const bytes = typeof content === "string" ? Buffer.from(content, "utf-8") : content;
  return createHash("sha256").update(normalizeLineEndings(bytes)).digest("hex");
}

/** `hashContent` of a file on disk. */
export async function hashFile(filePath: string): Promise<string> {
  return hashContent(await readFile(filePath));
}

/**
 * True when a file still matches a hash Arcane recorded for it -- the
 * line-ending-normalized digest (what `hashFile`/`copyFile` record now), or
 * the raw-bytes digest (what they recorded before normalization existed), so
 * an install that predates this change is read correctly without a
 * migration: a file byte-identical or LF-identical to what was recorded is
 * "untouched", and only genuinely different content reads as an edit.
 */
export async function fileMatchesHash(filePath: string, recordedHash: string): Promise<boolean> {
  const content = await readFile(filePath);
  if (hashContent(content) === recordedHash) return true;
  return createHash("sha256").update(content).digest("hex") === recordedHash;
}

/**
 * Validates that relativePath stays within targetDir.
 * Throws if the resolved path escapes the target directory boundary.
 */
export function validateTargetPath(
  targetDir: string,
  relativePath: string,
): void {
  const resolvedBase = path.resolve(targetDir);
  const resolvedFull = path.resolve(targetDir, relativePath);

  if (
    resolvedFull !== resolvedBase &&
    !resolvedFull.startsWith(resolvedBase + path.sep)
  ) {
    throw new Error(
      `Path traversal detected: "${relativePath}" escapes target directory "${targetDir}"`,
    );
  }
}

/**
 * Creates a directory and all parent directories if they don't exist.
 */
export async function ensureDir(dirPath: string): Promise<void> {
  await mkdir(dirPath, { recursive: true });
}

export async function fileExists(filePath: string): Promise<boolean> {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

/**
 * Copies srcPath into targetDir at relativePath.
 * Validates path traversal before any I/O.
 * Throws if the destination already exists and opts.force is not set.
 * Returns the copied content's SHA-256 hex digest (ARC-038 decision 1) --
 * read once into memory and reused for both the hash and the write, rather
 * than hashing srcPath and then separately copying it: reading every source
 * file twice measurably slowed a full `spell init` (~90 files) once every
 * file started being hashed, enough to push some CI/test runs over their
 * timeout under contention. One read, one write; no redundant I/O.
 */
export async function copyFile(
  srcPath: string,
  targetDir: string,
  relativePath: string,
  opts: { force?: boolean } = {},
): Promise<string> {
  validateTargetPath(targetDir, relativePath);

  const destPath = path.resolve(targetDir, relativePath);
  await ensureDir(path.dirname(destPath));

  if (!opts.force && (await fileExists(destPath))) {
    throw new Error(
      `Destination already exists: "${relativePath}". Use --force to overwrite.`,
    );
  }

  const content = await readFile(srcPath);
  const hash = hashContent(content);
  await writeFile(destPath, content);
  return hash;
}

/**
 * Deletes `relativePath` under `targetDir`, refusing (with the same named
 * error every write path already raises) any path that resolves outside it.
 * The paths this is called with come from `.arcane.json`, which is repository
 * content, so a manifest edited -- or generated by a hostile tool -- to track
 * `../../something` must never reach `rm` (TODO.md, "two delete paths apply
 * manifest-controlled paths without the traversal guard"). Missing files are
 * fine (`force`); nothing is ever removed recursively here.
 */
export async function removeWithin(targetDir: string, relativePath: string): Promise<void> {
  validateTargetPath(targetDir, relativePath);
  await rm(path.resolve(targetDir, relativePath), { force: true });
}

/**
 * Removes the directories a just-deleted file leaves behind, walking up from
 * its parent and stopping at the first non-empty one -- or at `targetDir`,
 * which is never removed. `rmdir` on purpose: it removes exactly an empty
 * directory and refuses a non-empty one, so a file that appears between the
 * emptiness check and the removal is never taken with it.
 *
 * Without this, pruning a component's files leaves its skeleton behind: a
 * repository that opts out of carrying spells (ARC-045 decision 4 / CS-05)
 * would keep 41 empty `.agents/skills/<id>/` directories and the empty
 * client folders above them, which git does not track and nothing else
 * cleans up.
 */
export async function removeEmptyAncestors(targetDir: string, relativePath: string): Promise<void> {
  validateTargetPath(targetDir, relativePath);
  const base = path.resolve(targetDir);
  let dir = path.dirname(path.resolve(targetDir, relativePath));
  while (dir !== base && dir.startsWith(base + path.sep)) {
    try {
      if ((await readdir(dir)).length > 0) return;
      await rmdir(dir);
    } catch {
      return; // already gone, unreadable, or no longer empty
    }
    dir = path.dirname(dir);
  }
}

export interface CopiedFile {
  path: string;
  hash: string;
}

/**
 * Recursively copies a directory from srcDir to targetDir/relativeDir.
 * Validates the target path to prevent traversal attacks.
 * Returns each copied file's relative path and content hash (ARC-038
 * decision 1), for manifest tracking.
 */
export async function copyDirectory(
  srcDir: string,
  targetDir: string,
  relativeDir: string,
  opts: { force?: boolean } = {},
): Promise<CopiedFile[]> {
  validateTargetPath(targetDir, relativeDir);

  const copiedFiles: CopiedFile[] = [];
  const entries = await readdir(srcDir, { withFileTypes: true });

  for (const entry of entries) {
    const srcEntryPath = path.join(srcDir, entry.name);
    const relEntryPath = `${relativeDir}/${entry.name}`;

    if (entry.isDirectory()) {
      const subFiles = await copyDirectory(srcEntryPath, targetDir, relEntryPath, opts);
      copiedFiles.push(...subFiles);
    } else {
      const hash = await copyFile(srcEntryPath, targetDir, relEntryPath, opts);
      copiedFiles.push({ path: relEntryPath, hash });
    }
  }

  return copiedFiles;
}
